name: Testes Cypress

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.4.1'  

    - name: Instalar dependências
      run: npm install

    - name: Rodar servidor
      run: npm start &
      
    - name: Esperar servidor iniciar
      run: sleep 10

    - name: Rodar testes Cypress
      run: npm run test:cypress
